### ISSUE TITLE
Why does the cast_slice parameter have to be of type Pod?

### ISSUE THREAD

**Issue by kwinz** [rust-lang/project-safe-transmute#13]
`pub fn try_cast_slice<A: Pod, B: Pod>(a: &[A]) -> Result<&[B], PodCastError>`
requires that the parameter `a` is a slice of type `Pod`. `Pod`s can't be `chars` (because the type must allow any bit pattern).

However I don't understand why. It's not like I can introduce illegal bit patterns through a non-mutable reference?!
Is this some random limitiation of this crate?

Can we not fix this because of [#41](https://github.com/Lokathor/bytemuck/issues/41)?
Is relaxing trait boundaries not allowed?

**Comment by jswrenn** [comment]
Did you mean to file this issue on [bytemuck](https://github.com/Lokathor/bytemuck)? 

This repo isn't for a crate; it tracks an effort to add a new analysis to rust itself.

**Comment by kwinz** [comment]
Yes you are right @jswrenn . Somehow I accidentally opened the issue in the wrong repository. And moreover since at least version 1.9.0 bytemuck actually changed the signature to take `NoUnit` instead of `Pod` to address exactly that. So the whole issue is moot in the first place.
I really shouldn't open issues when tired. Sorry for the noise! If you have the permission to delte my issue I would appreciate if you delete it.
