### ISSUE TITLE
Integrate prior art from Typic

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/project-safe-transmute#3]
[Typic](https://github.com/jswrenn/typic) seems to be [pushing the envelope](https://www.reddit.com/r/rust/comments/eh67wi/typic_safe_zerocost_transmutations/fcffj9y/) on what kind of transmutes can be made possible in safe Rust.

I'm opening this issue so that you're aware of it and can integrate it in the RFC as prior art.

**Comment by rylev** [comment]
#5 addresses this as it's directly inspired by Typic

**Comment by jswrenn** [comment]
Going to close this as completed! [`TransmuteFrom`](https://doc.rust-lang.org/nightly/std/mem/trait.TransmuteFrom.html) is essentially typic, but implemented in the compiler and far more powerful.
